# These are supported funding model platforms

github: [tanhongit]  # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., 
custom: ["https://www.paypal.me/tanhongit"] # Replace with up to 4 custom sponsorship URLs e.g.,
